### ISSUE TITLE
Navigation IE - Flèche directionnelle de scroll

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#13]
Sous IE la flèche qui permet le scroll ne fonctionne pas, je clique et rien ne se passe.

Les menus également ne fonctionnent pas, seul le scroll de la souris fonctionne

**Comment by PEM--** [comment]
Pas de possibilité de correction.

**Comment by JulietteASV** [comment]
Tant que le paiement marche ok mais c'est pas top.



2015-07-22 17:00 GMT+02:00 Pierre-Eric Marchandet <notifications@github.com>
:

**Comment by PEM--** [comment]
Je sais, c'est pas terrible. Merci Microsoft pour leur navigateur moisi.

**Comment by PEM--** [comment]
Leur prochaine version devrait être sur le même moteur que Chrome et Safari. Espérons qu'ils feront mieux.

**Comment by JulietteASV** [comment]
Oki
