### ISSUE TITLE
Iphone 5c Version 9.0 / Safari - Menu > Programme

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#18]
Attention quand on on clique dans le menu sur programme, le renvoi est fait sur la partie "présentation" il faut scroller pour atterrir sur programme.
Pas très gênant mais on s'y perd..

**Comment by PEM--** [comment]
C'était la demande dans la charte graphique. On change ? Si c'est gênant, tu peux modifier le titre du lien dans le backoffice.

**Comment by JulietteASV** [comment]
Si ct la demande, on laisse.
Ce n'est pas bloquant
