### ISSUE TITLE
Formulaire D'inscription - Modifs texte

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#2]
![inscription form - 20-07-2015](https://cloud.githubusercontent.com/assets/13415868/8773999/64020eec-2ed9-11e5-84ce-0b7363684aba.png)

La phrase de cet encadré ne me semble pas fonctionner, nous n'allons pas contacter les inscrits par téléphone pour leur confirmer leur inscription, d'autant plus qu'un email automatique leur sera envoyé...
Du coup, je pense que ces infos nous seront surtout nécessaires dans le cas où nous rencontrons un soucis avec l'inscription ou si nous avons besoin d'entrer plus en contact avec l'un des inscrits (jeu-concours, etc.)

Voilà ce que je verrais bien comme phrase : 
"Pour la bonne organisation de l'événement, nous pouvons être amené à vous contacter.
Merci d'indiquer vos modes préférés de contact : "

D'autres part, je pense qu'il faudrait laisser la possibilité de mettre les deux modes de contacts (mail et téléphone) de pouvoir cocher les deux si l'on souhaite et de n'avoir qu'un mode obligatoire pour s"inscrire.

**Comment by PEM--** [comment]
Pour le texte, sans problème. Pour la nouvelle structure d'information (nouvelle dynamique des champs), il me faudrait une journée supplémentaire.

**Comment by PEM--** [comment]
Le texte est trop long sur mobile. Je propose :
```text
Pour l'événement, nous pouvons être amené à vous contacter.
Merci d'indiquer vos modes préférés de contact :
```

**Comment by JulietteASV** [comment]
PEM, ok merci pour ces infos.
Du coup, avec Auré nous avons pensé que ces champs avaient surtout été pensés parce que nous voulions faire des pré-inscriptions. Vu que ce n'est plus le cas, voici ce que nous souhaiterions faire si ça ne demande pas de journée de dev supplémentaire;

Supprimer ces deux champs et cette phrase et ne rajouter qu'un champ en dessous du formulaire de base (à gauche) qui serait "numéro de téléphone" et qui serait obligatoire.

Qu'en penses-tu ?

**Comment by PEM--** [comment]
En fait, je doute que les utilisateurs laissent leur n° de téléphone. C'est un frein dans le funnel d'acquisition. On voit rarement le n° de téléphone dans les sites d'inscription (Meetup, Eventbrite, ...). En laissant le choix tel que ça a été pensé par Aurélie, tu es moins pushy vis-à-vis de tes utilisateurs.

Après, il faut vraiment voir si tu as besoin des n° de téléphone. Imagine que 400 inscrits te demande des contacts par téléphone, tu risque de passer tes journées à passer des coups de fil. En exprimant une préférence, tu ne t'interdits pas de les contacter aussi par mail.

**Comment by JulietteASV** [comment]
En fait, c'est vraiment si je rencontre des problèmes avec leur inscription et qu'ils ne me répondent par email.
Si cela ne rajoute pas du dev, on peut le mettre et le laisser non obligatoire, mais ça représente une sécurité pour nous dans le sens où s'il y a un pblm on peut joindre les gens.

**Comment by PEM--** [comment]
Heu... toute modification rajoute du dév... Dès que l'on fait un formulaire, il faut vérifier les champs, changer les styles smartphones et desktop, les transmettre au serveur, vérifier les failles de sécurité, insérer les données en base, les exposer sur le backoffice et si des données sont existantes, il faut prévoir une migration vers la nouvelle structure.

Comme nous sommes sur un forfait, il n'y a pas de surcoûts. Par contre, cela met juste plus de temps pour être terminé (on fait bouger la fin de la recette et donc la mise en production).

**Comment by JulietteASV** [comment]
Voilà la dead-line : 31 juillet 2015. Après cette date, je ne pourrais plus consacrer du temps aux tests sur le site, il doit donc être opérationnel pour fin juillet.

Du coup, si cela prends trop de temps, on laisse comme ça avec la nouvelle phrase et on garde ces infos pour une prochaine fois.

Si c'est possible, que cela rentre dans le forfait convenu entre Auré et toi, que la mise en place de cette demande ne prends pas trop de temps de test etc. go. Sinon on laisse comme ça.

Oki ?

**Comment by PEM--** [comment]
Pareil. Le 31 juillet, je serai sur la route des vacances. Donc, il faut qu'au max on finisse cette semaine pour que l'on se donne le temps de la mise à jour du serveur de production et que tu puisses faire ta campagne de communications.

**Comment by JulietteASV** [comment]
Ok du coup c'est jouable ou on laisse comme tel ?

**Comment by PEM--** [comment]
Moi, je laisserai comme tel parce que j'ai pas la moindre idée de ce que ça va donner sur les écrans :confused: Et que si je fais des tests en dévs, on va griller de précieuses journées. J'ai encore le paiement par carte à finir, SAGE, les champs animaux pour les ASV, le n° d'inscription plus friendly, ... Imagine en plus que tu vas devoir tester tout ça sur desktop et smartphone et à mon avis, on va finir par arriver fin Septembre. Pas super cool.

**Comment by JulietteASV** [comment]
Ok carrément d'accord avec toi !! 😊
