### ISSUE TITLE
PBLM Pas possible de valider le paiement

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#23]
![pas de validation de paiement](https://cloud.githubusercontent.com/assets/13415868/8848451/beb4b8b6-3137-11e5-809c-61350ab8d7db.png)
Impossible de valider mon paiement par cb, l'écran reste tel quel, le bouton de validation est coché donc grisé puis repasse au vert.
J'ai essayé de changer les chiffres de la date d'expiration pour en mettre des valides et cela ne fonctionne tout de même pas.

**Comment by PEM--** [comment]
Conséquence différente mais raison identique à #24.
