### ISSUE TITLE
Inscription qui n'apparaît pas 

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#24]
Je me suis inscrite avant de relancer les serveurs et mon inscription n'apparaît toujours pas.
je vais faire un test avec IE

**Comment by PEM--** [comment]
Est-ce que tu peux me donner les valeurs entrées pour que je fasse une reproduction du bug ?

**Comment by JulietteASV** [comment]
Nom : Rodriguez
Prénom : Baptiste
Choix : ASV Auxiliaire
email : apform1@apform.fr
Mode de paiement : chèque (car cb ne fonctionnait pas)

numéro de tel je sais plus ^^
j'ai choisi de m'inscrire à la newsletter



2015-07-23 12:56 GMT+02:00 Pierre-Eric Marchandet <notifications@github.com>
:

**Comment by PEM--** [comment]
L'adresse email était déjà utilisée. Notre protection anti-spam sur le serveur a empêché l'inscription en base de données.
