### ISSUE TITLE
Page payment - impossible de saisir du texte dans les champs CB

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#26]
C'est entrain de m'arriver en live, je ne peux rien entrer dans les champs, la barre verticale clignotte mais quand je tape sur mon clavier rien ne se passe.

Je suis sur Chrome et mon inscription est réalisée avec l'adresse email asvlasoiree@apform.fr

Nom CHROMEhabera
Prénom Juliette

**Comment by JulietteASV** [comment]
shame on me .................

**Comment by PEM--** [comment]
En fait, c'est un excellent test de robustesse... Comme quoi :wink:

**Comment by JulietteASV** [comment]
merci pour cette compassion ..😅
