### ISSUE TITLE
formulaire de contact - Mail envoyé (PAS URGENT)

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#3]
![contact - mail envoye](https://cloud.githubusercontent.com/assets/13415868/8776077/ac8aa48e-2eee-11e5-9b6c-29b35636f25c.png)

Je pense que tu nous as déjà expliqué que si l'utilisateur n'a pas la possibilité de renvoyer un email tout de suite après son premier envoi c'est pour ne pas être spamé.

Mais du coup, une fois que nous lui aurons re-répondu, il pourra de nouveau interagir avec nous par email ?

Merci

**Comment by PEM--** [comment]
Une fois que tu as son email et que tu lui a répondu, l'utilisateur a aussi ton email. Tu peux interagir avec lui autant que tu le juges nécessaires :wink:

**Comment by JulietteASV** [comment]
oui c'était pour être sûre, merci beaucoup. :)
