### ISSUE TITLE
Numéro de téléphone trop long

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#31]
Le champs numéro de téléphone n'est bloqué que dans le cas où l'utilisateur ne rentre pas un 06 ou un 0 n° de fixe. Mais il est possible de rentrer uns très longue série de numéro ex : 
0654785451354796965441223524856

Serait-il possible de bloquer cette saisie à une série de 10 chiffres commençant bien sûr par 0

**Comment by PEM--** [comment]
Corrigé et déployé.

**Comment by JulietteASV** [comment]
Nickel !

merci



2015-07-28 13:55 GMT+02:00 Pierre-Eric Marchandet <notifications@github.com>
:

**Comment by JulietteASV** [comment]
En effet c'est parfait ! Merci
