### ISSUE TITLE
Pas de n° de facture ds l'email transactionnel

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#32]
![pas de facture dans l email transac](https://cloud.githubusercontent.com/assets/13415868/8926213/568fba76-350e-11e5-9f82-075b0ddf7919.png)

Je n'ai pas reçu de numéro de facture dans mon email transactionnel, il y a-t-il un problème avec ma config Mandrill ? Pourrai-t-on se prendre 5 min pour regarder ça ensemble en visio ou quoi comme ça tu m'apprends et je ne t'embête plus ?

Merci

**Comment by JulietteASV** [comment]
Je viens de trouver, mes span se sont encore effacés... Je vais les remettre...

**Comment by PEM--** [comment]
:wink:

**Comment by JulietteASV** [comment]
oui je viens de refaire un test, bon Gmail est vraiment très fort il me
place mon email dans la barre des promotions... Alors qu'on a supprimé la
quasi totalité des images...
Mais bon ça me le fait aussi sur des grandes marques qui m'envoient des
factures d'achat..



2015-07-28 10:24 GMT+02:00 Pierre-Eric Marchandet <notifications@github.com>
:
