### ISSUE TITLE
Date d'expiration CB antérieure à 2015

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#33]
Je viens d'effectuer un test
Nom : Blablabla
Prénom : Lia
ID Braintree : 83141686
ID Transaction de paimement : byrv7d

J'ai rentré comme date d'expiration ; 05/78 et mon paiement à été validé.

Comment pouvons-nous régler cela ? Car j'ai peur de ne pas pouvoir faire la différence dans le back office si ce cas arrive.

**Comment by JulietteASV** [comment]
Alors, je suis allée voir dans Braintree, en fait quand je rentre les 2 derniers chiffres, lui prends en compte qu'il s'agit des années 2000, donc mon 78 s'est transformé en 2078, du coup mon paiement est passé!
Donc avec Auré on s'est dit que le plus important pour qu'un paiement soit valide, c'est que les numéros d'expiration ne précèdent pas l'année en cours, mais vu que c'est impossible avec Braintree c'est bien non ?
J'espère que tu comprendra mon explication ^^

**Comment by PEM--** [comment]
Ce sont des cartes de tests. Sur le compte de production et avec une vraie carte, ce cas n'arrivera pas. Le GIE déclarera la carte comme invalide. Braintree remontera l'information et nous affichons le fait que le paiement n'a pas été réalisé.

**Comment by JulietteASV** [comment]
Ok ça roule c'est super alors !
