### ISSUE TITLE
Plan soirée

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#5]
![plan plateforme](https://cloud.githubusercontent.com/assets/13415868/8776103/e1f027e8-2eee-11e5-9943-50fb0e889167.png)
Je trouve qu'il serait bien de rappeler l'adresse du lieu de la soirée à cet endroit, comme le fait google avec map où un carré apparaît à l'emplacement avec les coordonnées du bateau que voici :
 
La Plateforme
4 Quai Victor Augagneur, 69003 Lyon
04 37 40 13 93

Merci

**Comment by PEM--** [comment]
La charte graphique spécifiait ces informations à un autre endroit :
![capture d ecran 2015-07-21 a 07 53 03](https://cloud.githubusercontent.com/assets/227831/8793932/c63fdce8-2f7d-11e5-934e-c137352bd0ef.png)

**Comment by JulietteASV** [comment]
Oui je sais mais on a montré le site à d'autres personnes qui on fait cette remarque. Du coup, on pourrait juste le remettre à cet endroit non ?

**Comment by PEM--** [comment]
Je comprends bien. Moi aussi, je trouve bizarre d'avoir l'adresse dans le formulaire de contact. Par contre, il me faudrait une nouvelle charte graphique. En l'état, je ne vois pas trop où mettre les nouveaux blocs. Pour bien faire, il faudrait faire une charte qui représente les PC et les smartphones. Après, je pourrai estimer la charge de codage.

**Comment by JulietteASV** [comment]
Ok tant pis, je pense qu'il faut qu'on avance, on le prévoira pour la prochaine fois.

Je close l'issue
