### ISSUE TITLE
Google +

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#6]
![g](https://cloud.githubusercontent.com/assets/13415868/8778336/ac9a227e-2efd-11e5-8ebf-d6f00cf8790a.png)

J'ai mis les liens G+ de la page ASV la soirée, mais je ne savais pas quoi mettre pour le lien de l'auteur, donc j'ai mis le même.

Quand je clique sur l'icone G+ sur le site de test il me renvoie vers cette page : 
![g arrivee du lien](https://cloud.githubusercontent.com/assets/13415868/8778385/e9acf844-2efd-11e5-8a12-9a81625e6804.png)

Peux-tu m'aider sur cela ?

**Comment by PEM--** [comment]
Il faut mettre utiliser une URL du type : https://plus.google.com/b/117251567906459651437

**Comment by JulietteASV** [comment]
Oui mais dans quel lien ? Celui de l'auteur ou de l'éditeur ? ^^

**Comment by PEM--** [comment]
Tout dépend de la stratégie d'animation :
* Si tu mets la même chose pour l'auteur et l'éditeur, les +1 et les commentaires iront sur la même page.
* Si tu mets des pages différentes, ils sont partages sur plusieurs pages.

La seconde solution offre l'avantage à plusieurs personnes d'interagir avec les utilisateurs et d'accroitre le ranking. Mais elle a l'inconvénient d'être moins simple en terme d'interaction.

**Comment by JulietteASV** [comment]
Ok donc il faudrait mettre la page ASV + la page APForm, ?

**Comment by PEM--** [comment]
Je pense que ce serait pas mal. Après, il faut surtout voir si c'est OK pour toi d'avoir plusieurs sources d'échanges avec les utilisateurs.

**Comment by JulietteASV** [comment]
Oui c'est vrai que je préférerais qu'ils aillent uniquement sur ASV la soirée g+ donc je mets les deux mêmes.

**Comment by JulietteASV** [comment]
Une dernière chose, j'ai l'impression que si l'on a pas de compte google, on ne peut pas accéder à la page asv g+, j'ai essayé d'y accéder en étant déconnecté et google me demande de me connecter.
Peux-tu essayer ?

**Comment by PEM--** [comment]
Oui, là c'est comme pour FB ou Twitter. Si tu n'as pas de compte, le réseau social t'empêche de poster ou d'accéder.

**Comment by JulietteASV** [comment]
Ok ça marche.
Du coup, pour facebook dans le back office c'est pareil il faut ajouter le
champs facebook ou ça se fait tout seul avec les liens que je t'ai donné ?

**Comment by PEM--** [comment]
FB est moins exigeant. Les posts se font sur les pages des utilisateurs dans leur fil d'actu et en partage auprès de leurs amis, pas sur la page d'APForm. C'est plus casse-pied en community management parce que tu ne sais pas si l'on parle de toi sauf si tu utilises une plateforme du type [Mention](https://fr.mention.com/) ou autres.

Les informations de FB sont claqués dans l'OpenGraph : le titre, la description, une photo du site. Ce sont les mêmes infos que pour Twitter.

**Comment by JulietteASV** [comment]
Ok donc pas de manip supplémentaires à effectuer ?

**Comment by PEM--** [comment]
Normalement, aucune. J'ai mis une photo du site un peu bateau. Un screenshot du logo. Là, je pense que c'est améliorable. À voir si tu as des idées.

**Comment by JulietteASV** [comment]
Tu veux que je prépare quelque chose ?

**Comment by PEM--** [comment]
Regardes ce que ça donne en faisant un tweet et un partage FB sur un compte de tests. Comme ça tu peux checker si tu souhaites l'améliorer.

La photo courante est la suivante :
![twitter-card](https://cloud.githubusercontent.com/assets/227831/8797901/e7046784-2f9e-11e5-96dc-a47177560362.jpg)

**Comment by JulietteASV** [comment]
Ok c'est joli une fois publié.
