### ISSUE TITLE
Tailles de la police - Formulaire inscription

### ISSUE THREAD

**Issue by JulietteASV** [PEM--/asv-la-soiree#7]
Pourrais-tu grossir la police du formulaire d'inscription, car c'est vraiment petit et difficile à lire.

**Comment by PEM--** [comment]
L'augmentation de la police va générer un formulaire plus long (espace entre les champs de texte) qui sera supérieur à un écran desktop. Je propose de passer les textes de labels en majuscule.

**Comment by JulietteASV** [comment]
Oui je comprends, mais il faut trouver un moyen d'augmenter la lisibilité de ces champs car on ne les distingues pas bien.
Essayons de les passer en MAJ pour voir, mais cette request concerne surtout : 
- Le n° de promo
- Le "Nom de jeune fille"
- Prenom
- Email
- Numéro (dans le bloc à droite)

**Comment by PEM--** [comment]
Le passage en majuscule est fait et déployé :smile:

Par contre, si ce n'est pas bon, il va falloir se retaper la charte. Le dév s'est 3 à 5 fois le temps de la créa graphique. Grosso modo, il vaut mieux passer un peu de temps sur la charte pour éviter d'en perdre sur le dév.

**Comment by JulietteASV** [comment]
Ok ça marche je comprends.

Du coup il vaut mieux rester en minuscule avec une Maj en début de mot.
Sinon parfait
